import { useCallback, useEffect, useRef, useState } from 'react';
import {
  Alert,
  Button,
  Card,
  Segmented,
  Select,
  Slider,
  Space,
  Spin,
  Tag,
  Typography,
} from 'antd';
import { useTranslation } from '../lib/i18n/LanguageContext';
import {
  fetchReidBatch,
  fetchReidMeta,
  type ReidBatchResponse,
  type ReidMetaResponse,
  type ReidSplit,
  type ReidStage,
} from '../lib/api';
import ReidHeatmapCanvas, {
  type ReidDisplayMode,
} from '../components/reid/ReidHeatmapCanvas';
import NpuTopMonitor from '../components/reid/NpuTopMonitor';
import './ReidViz.css';

const STAGE_LABELS: Record<ReidStage, string> = {
  position_embedding: 'Position Embedding',
  transformer_0: 'Transformer 1',
  transformer_1: 'Transformer 2',
  classifier: 'Classifier Grad-CAM',
};

const STAGES: ReidStage[] = [
  'position_embedding',
  'transformer_0',
  'transformer_1',
  'classifier',
];

const DISPLAY_LABELS: Record<ReidDisplayMode, string> = {
  overlay: 'Overlay',
  heatmap: 'Heatmap',
  original: 'Original',
};

const errorText = (error: unknown) =>
  error instanceof Error ? error.message : 'Unable to load ReID visualization';

export default function ReidViz() {
  const { t } = useTranslation();
  const [meta, setMeta] = useState<ReidMetaResponse | null>(null);
  const [batch, setBatch] = useState<ReidBatchResponse | null>(null);
  const [split, setSplit] = useState<ReidSplit>('test');
  const [batchIndex, setBatchIndex] = useState(0);
  const [displayMode, setDisplayMode] = useState<ReidDisplayMode>('overlay');
  const [opacity, setOpacity] = useState(0.55);
  const [playing, setPlaying] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const requestSequence = useRef(0);

  const loadBatch = useCallback(async (nextIndex: number, nextSplit: ReidSplit) => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    const sequence = requestSequence.current + 1;
    requestSequence.current = sequence;
    setLoading(true);
    setError(null);
    try {
      const nextBatch = await fetchReidBatch(nextIndex, nextSplit, controller.signal);
      if (requestSequence.current !== sequence) return;
      setBatch(nextBatch);
      setBatchIndex(nextIndex);
    } catch (caught) {
      if (controller.signal.aborted) return;
      setError(errorText(caught));
      setPlaying(false);
    } finally {
      if (requestSequence.current === sequence) setLoading(false);
    }
  }, []);

  useEffect(() => {
    const controller = new AbortController();
    let active = true;
    setLoading(true);
    fetchReidMeta(controller.signal)
      .then((metadata) => {
        if (!active) return;
        setMeta(metadata);
        setSplit(metadata.defaultSplit);
        return loadBatch(0, metadata.defaultSplit);
      })
      .catch((caught) => {
        if (!controller.signal.aborted) setError(errorText(caught));
      })
      .finally(() => {
        if (active && !abortRef.current) setLoading(false);
      });
    return () => {
      active = false;
      controller.abort();
      abortRef.current?.abort();
    };
  }, [loadBatch]);

  const goToBatch = useCallback((requested: number) => {
    const total = batch?.totalBatches ?? meta?.totalBatches[split] ?? 0;
    if (total < 1 || loading) return;
    const wrapped = (requested + total) % total;
    void loadBatch(wrapped, split);
  }, [batch, loadBatch, loading, meta, split]);

  useEffect(() => {
    if (!playing || loading || !batch) return undefined;
    const timer = window.setTimeout(() => goToBatch(batchIndex + 1), 3500);
    return () => window.clearTimeout(timer);
  }, [batch, batchIndex, goToBatch, loading, playing]);

  const changeSplit = (value: ReidSplit) => {
    setPlaying(false);
    setSplit(value);
    void loadBatch(0, value);
  };

  return (
    <div className="reid-page">
      <div className="reid-heading">
        <div>
          <Typography.Title level={2}>{t('ReID Heatmap Visualization')}</Typography.Title>
          <Typography.Text type="secondary">
            {t('Four synchronized RGB/IR body heatmaps generated by the CPU ReID model.')}
          </Typography.Text>
        </div>
        {meta && <Tag color="blue">CPU · {meta.torchThreads} threads · 9×5 tokens</Tag>}
      </div>

      <NpuTopMonitor />

      <Card className="reid-controls">
        <Space wrap size="middle">
          <Select<ReidSplit>
            value={split}
            onChange={changeSplit}
            options={(meta?.splits ?? ['test']).map((value) => ({ value, label: value }))}
            style={{ width: 100 }}
          />
          <Button onClick={() => goToBatch(batchIndex - 1)} disabled={loading}>Previous batch</Button>
          <Button type="primary" onClick={() => goToBatch(batchIndex + 1)} disabled={loading}>Next batch</Button>
          <Button onClick={() => setPlaying((value) => !value)} disabled={!batch}>
            {playing ? 'Pause' : 'Play'}
          </Button>
          <Typography.Text>
            Batch {batchIndex + 1} / {batch?.totalBatches ?? meta?.totalBatches[split] ?? '—'}
          </Typography.Text>
        </Space>
        <div className="reid-control-row">
          <Segmented
            value={displayMode}
            onChange={(value) => setDisplayMode(value as ReidDisplayMode)}
            options={Object.entries(DISPLAY_LABELS).map(([value, label]) => ({ value, label }))}
          />
          <div className="reid-opacity">
            <Typography.Text>Overlay opacity</Typography.Text>
            <Slider
              min={0}
              max={1}
              step={0.05}
              value={opacity}
              disabled={displayMode !== 'overlay'}
              onChange={setOpacity}
            />
          </div>
        </div>
      </Card>

      {error && <Alert type="error" showIcon message={error} className="reid-alert" />}

      <Spin spinning={loading} tip={t('Generating heatmap...')}>
        <div className="reid-stage-list" aria-live="polite">
          {STAGES.map((stage) => (
            <section className="reid-stage-section" key={stage} aria-labelledby={`reid-stage-${stage}`}>
              <div className="reid-stage-note">
                <Typography.Title level={4} id={`reid-stage-${stage}`}>
                  {STAGE_LABELS[stage]}
                </Typography.Title>
                <span>{t('Heatmaps share one normalization range across all four samples in the batch.')}</span>
              </div>
              <div className="reid-sample-grid">
                {batch?.samples.map((sample, index) => (
                  <Card
                    key={sample.sampleId}
                    className="reid-sample-card"
                    title={`Sample ${index + 1} · PID ${sample.pid}`}
                    extra={<Tag color={sample.modality === 'visible' ? 'green' : 'purple'}>{sample.modality}</Tag>}
                  >
                    <ReidHeatmapCanvas
                      imageUrl={sample.imageUrl}
                      values={sample.heatmaps[stage].values}
                      mode={displayMode}
                      opacity={opacity}
                      label={`PID ${sample.pid} ${STAGE_LABELS[stage]} heatmap`}
                    />
                    <div className="reid-sample-meta">
                      <span>Camera {sample.camera}</span>
                      <span>Predicted PID {sample.prediction.pid}</span>
                      <span>Confidence {(sample.prediction.score * 100).toFixed(1)}%</span>
                    </div>
                  </Card>
                ))}
              </div>
            </section>
          ))}
        </div>
      </Spin>

      <div className="reid-legend">
        <span>Low</span><div className="reid-gradient" /><span>High</span>
        <Typography.Text type="secondary">Original spatial grid: 9×5 · Canvas: 256×256</Typography.Text>
      </div>
    </div>
  );
}
