/**
 * en.ts - 英文 i18n 文案 / English i18n strings
 *
 * i18next 文案资源:键值对,key 与 zh.ts 保持一致(便于运行时切换语言)。覆盖主
 * 页、提交、分类、注意力、GCN、IG、模型图、错误提示等所有可见文本。 / i18next
 * resource: key-value map, keys aligned with zh.ts (for runtime locale switch).
 * Covers all visible text: home, submit, classification, attention, GCN, IG,
 * model architecture, error messages, etc.
 *
 * 功能模块 / Modules:
 * - translation: 顶级命名空间 / top-level namespace
 * - 各功能模块的 key → 英文文案 / per-feature keys
 *
 * 输入 / Inputs:
 * - 无(纯数据模块)/ None, pure data module
 *
 * 输出 / Outputs:
 * - en: { translation: { ... } } - i18next 资源 / i18next resource
 *
 * 数据流 / Data Flow:
 * 1. i18next 初始化时加载本模块 / Loaded by i18next on init
 * 2. 组件调用 t('key') 时返回对应英文 / t('key') returns the English string
 *
 * 相关文件 / Related Files:
 * - 调用 / Calls: 无 / None
 * - 被调用 / Called by: i18n 初始化代码、各组件的 t() 调用 / i18n init, components via t()
 *
 * 使用示例 / Usage Example:
 *     import { en } from '@/lib/i18n/en';
 *     i18n.addResourceBundle('en', 'translation', en.translation);
 *     // 组件: t('Submit')
 *
 * 作者 / Author: 项目组 / Project Team
 * 版本 / Version: 1.0
 */
export const en = {
  translation: {
    'RNA Visualization': 'RNA Visualization',
    'Return to Home': 'Return to Home',
    // MainPage translations
    'RNA Sequence Analysis': 'RNA Sequence Analysis',
    'Enter RNA sequence': 'Enter RNA sequence',
    'Server': 'Server',
    'Server 1': 'Server 1',
    'Server 2': 'Server 2',
    'Server 3': 'Server 3',
    'Submit': 'Submit',
    'Submit task failed: {message}': 'Submit task failed: {message}',
    'Classification Results': 'Classification Results',
    'Attention Weights': 'Attention Weights',
    'GCN Graph Structure': 'GCN Graph Structure',
    'Integrated Gradients': 'Integrated Gradients',
    'Model Architecture': 'Model Architecture',
    // ReID translations
    'ReID Heatmap': 'ReID Heatmap Visualization',
    'ReID Heatmap Visualization': 'ReID Heatmap Visualization',
    'Visualize model attention across body regions to understand feature extraction patterns.': 'Visualize model attention across body regions to understand feature extraction patterns.',
    'Generating heatmap...': 'Generating heatmap...',
    'Heatmap Canvas': 'Heatmap Visualization',
    'Color Legend': 'Color Legend',
    'Four synchronized RGB/IR body heatmaps generated by the CPU ReID model.': 'Four synchronized RGB/IR body heatmaps generated by the CPU ReID model.',
    'Heatmaps share one normalization range across all four samples in the batch.': 'Heatmaps share one normalization range across all four samples in the batch.',
    // End ReID translations
    'No RNA sequence provided.': 'No RNA sequence provided.',
    'Please select a target class ID.': 'Please select a target class ID.',
    'Failed to compute Integrated Gradients: {message}': 'Failed to compute Integrated Gradients: {message}',
    'Error': 'Error',
    'Please enter an RNA sequence.': 'Please enter an RNA sequence.',
    'Integrated Gradients Controls': 'Integrated Gradients Controls',
    'Target Class ID:': 'Target Class ID:',
    'Select Target Class': 'Select Target Class',
    'Show Top': 'Show Top',
    'nodes': 'nodes',
    'Compute': 'Compute',
    'Statistics:': 'Statistics:',
    'Target Class:': 'Target Class:',
    'Total Nodes:': 'Total Nodes:',
    'Total Edges:': 'Total Edges:',
    'Highlight:': 'Highlight:',
    ' nodes (2x larger, opaque)': ' nodes (2x larger, opaque)',
    'Other Nodes:': 'Other Nodes:',
    ' nodes (translucent)': ' nodes (translucent)',
    'Computing Integrated Gradients...': 'Computing Integrated Gradients...',
    'Node Attribution Scores (Top {topN})': 'Node Attribution Scores (Top {topN})',
    'Rank': 'Rank',
    'Node ID': 'Node ID',
    'Type': 'Type',
    'Position': 'Position',
    'Attribution Score': 'Attribution Score',
    'Failed to load data: {message}': 'Failed to load data: {message}',
    'Loading sequence data...': 'Loading sequence data...',
    'Visualization Controls': 'Visualization Controls',
    'modification sites': 'modification sites',
    'Select Modification Type:': 'Select Modification Type:',
    'All Modifications': 'All Modifications',
    'Select modification type:': 'Select modification type:',
    'Select modification type': 'Select modification type',
    'Available modification types: ': 'Available modification types: ',
    'None': 'None',
    '(Raw predictions: {predictions})': '(Raw predictions: {predictions})',
    'Previous': 'Previous',
    'Viewing: {current} / {total}': 'Viewing: {current} / {total}',
    'Next': 'Next',
    'Viewing modification type: ': 'Viewing modification type: ',
    'Render Debug Info:': 'Render Debug Info:',
    'Sequence Length: ': 'Sequence Length: ',
    'Current Highlight: ': 'Current Highlight: ',
    'Position {index}, Type {type}': 'Position {index}, Type {type}',
    'Viewport Element Count: ': 'Viewport Element Count: ',
    'Modification Site Statistics': 'Modification Site Statistics',
    'Original Sequence Length: ': 'Original Sequence Length: ',
    'Total detected weight data: ': 'Total detected weight data: ',
    'Selected modification type: ': 'Selected modification type: ',
    'Currently showing Top: ': 'Currently showing Top: ',
    'Actually showing: ': 'Actually showing: ',
    ' modification sites': ' modification sites',
    'List of currently displayed modification sites (normalized by nucleotide group):': 'List of currently displayed modification sites (normalized by nucleotide group):',
    'Position: {index},': 'Position: {index},',
    'Raw score: {score}': 'Raw score: {score}',
    'No significant modification sites detected for the selected nucleotide group.': 'No significant modification sites detected for the selected nucleotide group.',
    'No significant modification sites detected.': 'No significant modification sites detected.',
    'Current sequence length: {length} | Top setting: {topX} | Total weight data: {totalWeights}': 'Current sequence length: {length} | Top setting: {topX} | Total weight data: {totalWeights}',
    'Hint: The currently selected modification type {type} does not contain available attention data.': 'Hint: The currently selected modification type {type} does not contain available attention data.',
    // ResultsPage translations
    'Results calculation in progress, please wait...': 'Results calculation in progress, please wait...',
    'Task ID:': 'Task ID:',
    'Processing failed': 'Processing failed',
    'Unable to load data': 'Unable to load data',
    'Processing timeout': 'Processing timeout',
    'Task processing timeout, please try again later': 'Task processing timeout, please try again later',
    'No data': 'No data',
    'Unable to load visualization data': 'Unable to load visualization data',
    'RNA Sequence Analysis Results': 'RNA Sequence Analysis Results',
    'Visualization Options': 'Visualization Options',
    'Classification Tree': 'Classification Tree',
    'Attention': 'Attention',
    'GCN Graph': 'GCN Graph',
    // Additional translations
    'Unable to load attention data: {message}': 'Unable to load attention data: {message}',
    'Loading chart...': 'Loading chart...',
    'Unable to load chart data: {message}': 'Unable to load chart data: {message}',
    '✓ Predicted': '✓ Predicted',
    '✗ Not predicted': '✗ Not predicted',
    'Loading graph data...': 'Loading graph data...',
    'Unable to load graph data: {message}': 'Unable to load graph data: {message}',
    'Normal: {score}': 'Normal: {score}',
    'Original: {score}': 'Original: {score}',
    'Index: {index}': 'Index: {index}',
    // ModelViz translations
    'View Model Architecture': 'View Model Architecture',
    'Model Graph Visualization': 'Model Graph Visualization',
    'Interactive data flow visualization of RNA_ClassQuery_Model': 'Interactive data flow visualization of RNA_ClassQuery_Model',
    'Loading model graph...': 'Loading model graph...',
    'Failed to load model graph: {message}': 'Failed to load model graph: {message}',
    // TargetGcnViz translations
    'Loading GCN aggregation data...': 'Loading GCN aggregation data...',
    'Please provide RNA sequence and target node index.': 'Please provide RNA sequence and target node index.',
    'Failed to load GCN aggregation data: {message}': 'Failed to load GCN aggregation data: {message}',
    'Layer': 'Layer',
    'Play': 'Play',
    'Pause': 'Pause',
    'Message Details': 'Message Details',
    'Source Node': 'Source Node',
    'Nucleotide': 'Nucleotide',
    'Message Strength': 'Message Strength',
    'Legend': 'Legend',
    'Target Node': 'Target Node',
    'Normal Node': 'Normal Node',
    'Source Node (Active)': 'Source Node (Active)',
    'Normal Edge': 'Normal Edge',
    'Active Edge (Animated)': 'Active Edge (Animated)',
    'GCN Message Passing': 'GCN Message Passing',
    'Target GCN': 'Target GCN',
    'Target Node Index': 'Target Node Index',
    'Enter target node index': 'Enter target node index',
    'Range': 'Range',
    'Enter a node index to visualize message passing from its neighbors through GCN layers': 'Enter a node index to visualize message passing from its neighbors through GCN layers',
    'Tip: You can also click on any node in the graph to select it as the target node.': 'Tip: You can also click on any node in the graph to select it as the target node.',
    'Current selected': 'Current selected',
    'Neighbor Node': 'Neighbor Node',
    'Hop Neighbors': 'Hop Neighbors',
    '1-Hop': '1-Hop',
    '2+ Hop': '2+ Hop',
    'High Strength': 'High Strength',
    'Medium Strength': 'Medium Strength',
    'Low Strength': 'Low Strength',
    'Links': 'Links',
    'Target': 'Target',
    'Normal': 'Normal',
    'Color intensity/opacity represents message passing strength or distance to target node.': 'Color intensity/opacity represents message passing strength or distance to target node.',
    '...': '...',
    'Drag to rotate • Scroll to zoom • Right-click drag to pan • Click node to select as target': 'Drag to rotate • Scroll to zoom • Right-click drag to pan • Click node to select as target',
    // GcnViz legend translations
    'Nucleotide Legend': 'Nucleotide Legend',
    'Backbone': 'Backbone',
    'Pairing': 'Pairing',
    // Compare page translations
    'Model Performance Comparison': 'Model Performance Comparison',
    'Compare Page': 'Compare Page',
    'Compare model performance': 'Compare model performance',
    'Bar Chart': 'Bar Chart',
    'Loading comparison data...': 'Loading comparison data...',
    'Failed to load comparison data': 'Failed to load comparison data',
    // New heatmap page translations
'DCPRES Classification': 'DCPRES Classification',
'DCPRES Classification Performance': 'DCPRES Classification Performance',
    // Localization translations
    'Localization': 'Localization',
    'Localization Performance': 'Localization Performance',
    'Reference': 'Reference',
    // Loc Comparison translations
    'Loc Comparison': 'Loc Comparison',
    'Localization Model Comparison': 'Localization Model Comparison',
    // UMAP translations
    'UMAP Visualization': 'UMAP Visualization',
    'CORA UMAP Visualization': 'CORA UMAP Visualization',
    'Total points': 'Total points',
    'Per class': 'Per class',
    'Loading UMAP data...': 'Loading UMAP data...',
    'Failed to load UMAP data': 'Failed to load UMAP data',
  },
};
