/**
 * zh.ts - 中文 i18n 文案 / Chinese i18n strings
 *
 * i18next 中文文案资源,与 en.ts 共享同一套 key,运行时根据用户偏好切换。
 * 覆盖所有 UI 文本。 / i18next Chinese resource. Shares the same keys as en.ts;
 * switched at runtime by user preference. Covers all UI text.
 *
 * 功能模块 / Modules:
 * - translation: 顶级命名空间 / top-level namespace
 * - 各功能模块的 key → 中文文案 / per-feature keys
 *
 * 输入 / Inputs:
 * - 无(纯数据模块)/ None, pure data module
 *
 * 输出 / Outputs:
 * - zh: { translation: { ... } } - i18next 资源 / i18next resource
 *
 * 数据流 / Data Flow:
 * 1. i18next 初始化时加载 / Loaded by i18next on init
 * 2. t('key') 返回对应中文 / t('key') returns the Chinese string
 *
 * 相关文件 / Related Files:
 * - 调用 / Calls: 无 / None
 * - 被调用 / Called by: i18n 初始化代码、各组件的 t() / i18n init, components via t()
 *
 * 使用示例 / Usage Example:
 *     import { zh } from '@/lib/i18n/zh';
 *     i18n.addResourceBundle('zh', 'translation', zh.translation);
 *
 * 作者 / Author: 项目组 / Project Team
 * 版本 / Version: 1.0
 */
export const zh = {
  translation: {
    'RNA Visualization': 'RNA 可视化',
    'Return to Home': '返回主页',
    // MainPage 翻译
    'RNA Sequence Analysis': 'RNA 序列分析',
    'Enter RNA sequence': '输入 RNA 序列',
    'Server': '服务器',
    'Server 1': '服务器 1',
    'Server 2': '服务器 2',
    'Server 3': '服务器 3',
    'Submit': '提交',
    'Submit task failed: {message}': '提交任务失败: {message}',
    'Classification Results': '分类结果',
    'Attention Weights': '注意力权重',
    'GCN Graph Structure': 'GCN图结构',
    'Integrated Gradients': 'Integrated Gradients',
    'Model Architecture': '模型架构',
    // ReID translations
    'ReID Heatmap': 'ReID热力图可视化',
    'ReID Heatmap Visualization': 'ReID热力图可视化',
    'Visualize model attention across body regions to understand feature extraction patterns.': '可视化模型在身体各区域的注意力分布，以理解特征提取模式。',
    'Generating heatmap...': '生成热力图中...',
    'Heatmap Canvas': '热力图可视化',
    'Color Legend': '颜色图例',
    'Four synchronized RGB/IR body heatmaps generated by the CPU ReID model.': 'CPU ReID 模型生成的四张 RGB/IR 人体热力图将同步更新。',
    'Heatmaps share one normalization range across all four samples in the batch.': '同一批次的四个样本共享当前层的归一化范围。',
    // End ReID translations
    'No RNA sequence provided.': '未提供RNA序列。',
    'Please select a target class ID.': '请选择目标类别ID。',
    'Failed to compute Integrated Gradients: {message}': '无法计算 Integrated Gradients: {message}',
    'Error': '错误',
    'Please enter an RNA sequence.': '请输入RNA序列。',
    'Integrated Gradients Controls': 'Integrated Gradients 控制',
    'Target Class ID:': '目标类别 ID:',
    'Select Target Class': '选择目标类别',
    'Show Top': '显示 Top',
    'nodes': '个节点',
    'Compute': '计算',
    'Statistics:': '统计信息:',
    'Target Class:': '目标类别:',
    'Total Nodes:': '节点总数:',
    'Total Edges:': '边总数:',
    'Highlight:': '高亮显示:',
    ' nodes (2x larger, opaque)': ' 个节点 (大2倍，不透明)',
    'Other Nodes:': '其他节点:',
    ' nodes (translucent)': ' 个节点 (半透明)',
    'Computing Integrated Gradients...': '正在计算 Integrated Gradients...',
    'Node Attribution Scores (Top {topN})': '节点属性分数 (Top {topN})',
    'Rank': '排名',
    'Node ID': '节点ID',
    'Type': '类型',
    'Position': '位置',
    'Attribution Score': '属性分数',
    'Failed to load data: {message}': '无法加载数据: {message}',
    'Loading sequence data...': '正在加载序列数据...',
    'Visualization Controls': '可视化控制',
    'modification sites': '个修饰位点',
    'Select Modification Type:': '选择修饰类型:',
    'All Modifications': '所有修饰',
    'Select modification type:': '选择修饰类型:',
    'Select modification type': '选择修饰类型',
    'Available modification types: ': '可用修饰类型: ',
    'None': '无',
    '(Raw predictions: {predictions})': '(原始预测: {predictions})',
    'Previous': '上一个',
    'Viewing: {current} / {total}': '当前查看: 第 {current} / {total} 个',
    'Next': '下一个',
    'Viewing modification type: ': '当前查看修饰类型: ',
    'Render Debug Info:': '渲染调试信息:',
    'Sequence Length: ': '序列长度: ',
    'Current Highlight: ': '当前高亮: ',
    'Position {index}, Type {type}': '位置 {index}, 类型 {type}',
    'Viewport Element Count: ': '视口元素数量: ',
    'Modification Site Statistics': '修饰位点统计',
    'Original Sequence Length: ': '原始序列长度: ',
    'Total detected weight data: ': '检测到的权重数据总数: ',
    'Selected modification type: ': '选中的修饰类型: ',
    'Currently showing Top: ': '当前显示 Top: ',
    'Actually showing: ': '实际显示: ',
    ' modification sites': '个修饰位点',
    'List of currently displayed modification sites (normalized by nucleotide group):': '当前显示的修饰位点列表 (同组核苷酸归一化):',
    'Position: {index},': '位置: {index},',
    'Raw score: {score}': '原始得分: {score}',
    'No significant modification sites detected for the selected nucleotide group.': '选中的修饰类型对应的核苷酸组没有检测到显著修饰位点',
    'No significant modification sites detected.': '没有检测到显著修饰位点',
    'Current sequence length: {length} | Top setting: {topX} | Total weight data: {totalWeights}': '当前序列长度: {length} | Top设置: {topX} | 权重数据总数: {totalWeights}',
    'Hint: The currently selected modification type {type} does not contain available attention data.': '提示: 当前选择的修饰类型 {type} 不包含可用的注意力数据',
    // ResultsPage 翻译
    'Results calculation in progress, please wait...': '结果计算中，请稍候...',
    'Task ID:': '任务 ID:',
    'Processing failed': '处理失败',
    'Unable to load data': '无法加载数据',
    'Processing timeout': '处理超时',
    'Task processing timeout, please try again later': '任务处理超时，请稍后重试',
    'No data': '无数据',
    'Unable to load visualization data': '无法加载可视化数据',
    'RNA Sequence Analysis Results': 'RNA 序列分析结果',
    'Visualization Options': '可视化选项',
    'Classification Tree': '分类树',
    'Attention': '注意力',
    'GCN Graph': 'GCN图',
    // Additional translations
    'Unable to load attention data: {message}': '无法加载注意力数据: {message}',
    'Loading chart...': '正在加载图表...',
    'Unable to load chart data: {message}': '无法加载图表数据: {message}',
    '✓ Predicted': '✓ 已预测',
    '✗ Not predicted': '✗ 未预测',
    'Loading graph data...': '正在加载图数据...',
    'Unable to load graph data: {message}': '无法加载图数据: {message}',
    'Normal: {score}': '归一化: {score}',
    'Original: {score}': '原始: {score}',
    'Index: {index}': '索引: {index}',
    // ModelViz 翻译
    'View Model Architecture': '查看模型架构',
    'Model Graph Visualization': '模型图可视化',
    'Interactive data flow visualization of RNA_ClassQuery_Model': 'RNA_ClassQuery_Model 的交互式数据流可视化',
    'Loading model graph...': '正在加载模型图...',
    'Failed to load model graph: {message}': '无法加载模型图: {message}',
    // TargetGcnViz 翻译
    'Loading GCN aggregation data...': '正在加载 GCN 聚合数据...',
    'Please provide RNA sequence and target node index.': '请提供 RNA 序列和目标节点索引。',
    'Failed to load GCN aggregation data: {message}': '无法加载 GCN 聚合数据: {message}',
    'Layer': '层',
    'Play': '播放',
    'Pause': '暂停',
    'Message Details': '消息详情',
    'Source Node': '源节点',
    'Nucleotide': '核苷酸',
    'Message Strength': '消息强度',
    'Legend': '图例',
    'Target Node': '目标节点',
    'Normal Node': '普通节点',
    'Source Node (Active)': '源节点（活跃）',
    'Normal Edge': '普通边',
    'Active Edge (Animated)': '活跃边（动画）',
    'GCN Message Passing': 'GCN 消息传递',
    'Target GCN': 'GCN 消息传递',
    'Target Node Index': '目标节点索引',
    'Enter target node index': '输入目标节点索引',
    'Range': '范围',
    'Enter a node index to visualize message passing from its neighbors through GCN layers': '输入节点索引以可视化来自其邻居通过 GCN 层的消息传递',
    'Tip: You can also click on any node in the graph to select it as the target node.': '提示：您也可以点击图中的任意节点将其选择为目标节点。',
    'Current selected': '当前选择',
    'Neighbor Node': '邻居节点',
    'Hop Neighbors': '跳数邻居',
    '1-Hop': '1跳',
    '2+ Hop': '2+跳',
    'High Strength': '高强度',
    'Medium Strength': '中等强度',
    'Low Strength': '低强度',
    'Links': '连接边',
    'Target': '目标',
    'Normal': '普通',
    'Color intensity/opacity represents message passing strength or distance to target node.': '颜色深浅/透明度代表信息传递强度或与目标节点的距离。',
    '...': '...',
    'Drag to rotate • Scroll to zoom • Right-click drag to pan • Click node to select as target': '拖动旋转 • 滚轮缩放 • 右键拖动平移 • 点击节点选择为目标节点',
    // GcnViz legend translations
    'Nucleotide Legend': '核苷酸图例',
    'Backbone': '主链',
    'Pairing': '配对',
    // Compare page translations
    'Model Performance Comparison': '模型性能比较',
    'Compare Page': '模型比较',
    'Compare model performance': '比较模型性能',
    'Bar Chart': '柱状图',
    'Loading comparison data...': '正在加载比较数据...',
    'Failed to load comparison data': '加载比较数据失败',
    // New heatmap page translations
'DCPRES Classification': 'DCPRES 分类性能',
'DCPRES Classification Performance': 'DCPRES 分类性能详情',
    // Localization translations
    'Localization': '定位性能',
    'Localization Performance': '定位性能详情',
    'Reference': '参考',
    // Loc Comparison translations
    'Loc Comparison': '定位比较',
    'Localization Model Comparison': '定位模型比较',
    // UMAP translations
    'UMAP Visualization': 'UMAP 可视化',
    'CORA UMAP Visualization': 'CORA UMAP 可视化',
    'Total points': '总点数',
    'Per class': '每类',
    'Loading UMAP data...': '正在加载 UMAP 数据...',
    'Failed to load UMAP data': '加载 UMAP 数据失败',
  },
};
